### ISSUE TITLE
`java.lang.NoSuchMethodError` when invoking webhook endpoint with Spring Boot 3

### ISSUE THREAD

**Issue by chillleader** [camunda-community-hub/spring-zeebe#404]
### Steps to reproduce
1. Build a runtime with Spring Boot 3
2. Deploy a process with inbound webhook connector
3. Call the webhook connector endpoint and no matter the outcome receive 500 status code.

Logs contain:
```
java.lang.NoSuchMethodError: 'void org.springframework.web.server.ResponseStatusException.<init>(org.springframework.http.HttpStatus, java.lang.String)'
	at io.camunda.connector.runtime.inbound.webhook.InboundWebhookRestController.inbound(InboundWebhookRestController.java:80)
```
### Cause

Spring Boot 3 uses Spring Web 6.0.7. In this version of Spring Web, the following change was made in [this commit](https://github.com/spring-projects/spring-framework/commit/28ac0d3883e0c683fb995dffc0af7c8a82f3c3d0#diff-15fb957123f718e8cd452619b5959c4fadd0ec0073e1f3f7745651762f0eda9e):
- `ResponseEntity.status(HttpStatus)` method was replaced with `ResponseEntity.status(HttpStatusCode)` (new class, missing in old Spring Web
- `ResponseStatusException` constructor was also changed to consume `HttpStatusCode` instead of `HttpStatus`.

Because of this, code that compiles with Spring Boot 2.7 fails in runtime with Spring Boot 3.

### Proposed solution

Use other methods of `ResponseEntity` and `ResponseStatusException` which are compatible with both Spring Boot versions.
